server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: Api-GateWay


  cloud:
    gateway:
      routes:
        - id: loan-service
          uri: lb://loan-service
          predicates:
              - Path=/loan/**
              
        - id: customer-service
          uri: lb://customer-service
          predicates:
              - Path=/customers/**



